# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b4aa5c482365923770c0f0c4fbacfde17b962858358c0eded5221e3b6b517ff1efd44b022e5c85735abd6f2b89d9156ca730fe27345d490cec34929397486a

test:
  secret_key_base: e5602ecd64fa62e1fa11a3b23a16cff35a1650b6ec35fbf585ad854e7533a506eeb70eb29fc8655c393690965f548cb0523881138169ed52f3fcc84c3e6bfb22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
